### ISSUE TITLE
Hard to read due to outdated language

### ISSUE THREAD

**Issue by L3P3** [Spickelbing/vocparse#1]
In order to understand the application better, it would be nice to reimplement it in another one, like JavaScript or from me out Python.
And where is the Haskell variant? lol

**Comment by Spickelbing** [comment]
outdated language my a**

**Comment by Spickelbing** [comment]
maybe Python though

**Comment by Spickelbing** [comment]
reimplementing it in Python isn't a bad idea though

**Comment by L3P3** [comment]
A'right, will open another issue for Python then as JavaScript is better than Python.

**Comment by Spickelbing** [comment]
At that point you could translate the Python code into JavaScript yourself

**Comment by L3P3** [comment]
No need for that buddy, already have a somewhat working JavaScript implementation at hands. :sunglasses:

**Comment by Spickelbing** [comment]
then we're done here

**Comment by L3P3** [comment]
I reopened in order to close it.
